config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'reader', to: 'home#reader', as: :reader

  resources :feeds
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :feed_items, dependent: :delete_all

  after_create_commit :schedule_feed_job

  private

  def schedule_feed_job
    FeedJob.perform_later(id)
  end
end

app/models/feed_item.rb
class FeedItem < ApplicationRecord
  belongs_to :feed

  validates_presence_of :guid, :title, :link

  scope :all_recent, -> { order('pub_date desc') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :find_feed, except: %i[index create]

  def index
    render json: Feed.all
  end

  def show
    render json: @feed
  end

  def create
    @feed = Feed.create(feed_params)
    render json: @feed, status: :created
  end

  def update
    @feed.update(feed_params)
    render json: @feed, status: :ok
  end

  def destroy
    @feed.destroy
    head :no_content
  end

  rescue_from ActiveRecord::RecordNotFound do |e|
    render json: { error: e.message }, status: :not_found
  end

  rescue_from ActiveRecord::RecordInvalid do |e|
    render json: { error: e.message }, status: :forbidden
  end

  private

  def feed_params
    params.permit(:url)
  end

  def find_feed
    @feed = Feed.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  layout 'application'

  def index

  end

  def reader
    @articles = FeedItem.all_recent
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%= react_component("Feeds") %>

app/views/home/reader.html.erb
<table>
  <%- @articles.each do |article| %>
    <tr>
      <td>
        <%= link_to(article.title, article.link, target: '_blank') %>
      </td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to('Feed Manager', '/') %>
    &nbsp;|&nbsp;
    <%= link_to('Reader Page', reader_path) %>
    <br/>
    <br/>
    <%= yield %>
  </body>
</html>